version: '1.0'
name: pipeline-20230510
displayName: pipeline-20230510
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - alpha
stages:
  - name: stage-b7322326
    displayName: cargo_test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: cargo test
        hostGroupID:
          ID: alibaba
          hostID:
            - 34e89604-1c2e-4fba-8075-369f96fd3cc7
        script:
          - git clone git@gitee.com:YanDevelop/sysyc.git
          - cd sysyc
          - cargo test
        notify: []
        strategy:
          retry: '0'
          timeout: 5
