// Generated by Flexc++ V2.07.07 on Wed, 02 Apr 2025 14:06:07 +0000

#ifndef Scanner_H_INCLUDED_
#define Scanner_H_INCLUDED_

// $insert baseclass_h
#include "errmsg.h"
#include "scannerbase.h"

#include "myparserbase.h"
#include <fstream>
#include <istream>
#include <memory>
#include <ostream>

// $insert classHead
class Scanner: public ScannerBase
{
    public:
        // explicit Scanner(std::istream &in = std::cin,
        //                         std::ostream &out = std::cout);

        // Scanner(std::string const &infile, std::string const &outfile);
        Scanner() = delete;
        explicit Scanner(std::string fname, std::ostream &out = std::cout)
            : ScannerBase(std::cin,out), pos(0), buf(""), fin(fname), 
            errmsg(std::make_unique<frontend::err::ErrMsg>()) {
            switchStreams(fin,out);
        }

        explicit Scanner(std::istream &in = std::cin, std::ostream &out = std::cout)
            : ScannerBase(std::cin,out), pos(0), buf(""), 
            errmsg(std::make_unique<frontend::err::ErrMsg>()) {
            switchStreams(in,out);
        }
        
        // $insert lexFunctionDecl
        int lex();

    private:
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.

    /*****above is generated by flexc++*****/
    public:
        std::unique_ptr<frontend::err::ErrMsg> transferErrMsg();
        int getPos() const { return pos; }
    private:
        void adjust(bool update);
    
        int pos;
        std::string buf;
        std::ifstream fin;
        std::unique_ptr<frontend::err::ErrMsg> errmsg;
};

// $insert scannerConstructors
// inline Scanner::Scanner(std::istream &in, std::ostream &out)
// :
//     ScannerBase(in, out)
// {}

// inline Scanner::Scanner(std::string const &infile, std::string const &outfile)
// :
//     ScannerBase(infile, outfile)
// {}

// $insert inlineLexFunction
inline int Scanner::lex()
{
    return lex_();
}

inline void Scanner::preCode() 
{
    // optionally replace by your own code
}

inline void Scanner::postCode([[maybe_unused]] PostEnum_ type) 
{
    // optionally replace by your own code
}

inline void Scanner::print() 
{
    print_();
}

inline void Scanner::adjust(bool update = true) {
    if(update) {
        errmsg->token_pos = pos;
    }
    pos += length();
}

inline std::unique_ptr<frontend::err::ErrMsg> Scanner::transferErrMsg() {
    return std::move(errmsg);
}


#endif // Scanner_H_INCLUDED_

