// Generated by Bisonc++ V6.03.00 on Wed, 02 Apr 2025 14:06:07 +0000

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "AST/decl.h"
#include "myparserbase.h"
// $insert scanner.h
#include "errmsg.h"
#include "scanner.h"
#include <cassert>
#include <istream>
#include <memory>
#include <ostream>
#include <string>
#include <map>
#include <string>

#undef Parser
    // CAVEAT: between the baseclass-include directive and the 
    // #undef directive in the previous line references to Parser 
    // are read as ParserBase.
    // If you need to include additional headers in this file 
    // you should do so after these comment-lines.


class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;
        
    public:
        Parser() = default;
        int parse();

    private:
        void error();                   // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc
        void exceptionHandler(std::exception const &exc);

    // support functions for parse():
        void executeAction_(int ruleNr);
        void errorRecovery_();
        void nextCycle_();
        void nextToken_();
        void print_();

    /*above is generated by bisonc++*/
    public:
        Parser(std::string fname, std::ostream &out = std::cout):
            d_scanner(fname,out) {}
        Parser(std::istream &in, std::ostream &out = std::cout):
            d_scanner(in,out) {} 
        std::unique_ptr<frontend::err::ErrMsg> transferErrMsg() {
            return std::move(d_scanner.transferErrMsg());
        }
        TUDecl *getTUDecl() { return TU; }
    private:
        std::list<std::string> string_pool;
        int current_token = 0;
        TUDecl *TU;
};

inline void Parser::error() {
    // std::cout << d_scanner.lineNr() <<  std::endl;
    std::unique_ptr<frontend::err::ErrMsg> errmsg = d_scanner.transferErrMsg();
    std::map<int, std::string> tokname = {
        #define TOKNAME(tok) { Parser::tok, #tok },
        #include "TOKNAME.inc"
        #undef TOKNAME
    };
    errmsg->InsertErrAt(d_scanner.getPos(), "syntax error current token " + tokname[current_token]);
    errmsg->traverse([](std::string msg) {
        std::cout << msg << std::endl;
    });
    // assert(false && "syntax error");
    exit(1);
}

inline int Parser::lex() {
    int token = d_scanner.lex();
    switch (token) {
        case Parser::INT: {
            d_val_.ival = std::stoi(d_scanner.matched(), nullptr, 0);
            std::cout << "int " << d_scanner.matched() << " " << d_val_.ival << std::endl;
            break;
        }
        case Parser::FLOAT:
            d_val_.dval = std::stod(d_scanner.matched());
            std::cout << "float " << d_scanner.matched() << " " << d_val_.dval << std::endl;
            break;
        case Parser::IDENT:
            string_pool.push_back(d_scanner.matched());
            d_val_.sval = &string_pool.back();
            break;
        default:
            break;
    }
    current_token = token;
    return token;
}

inline void Parser::print() { print_(); }

inline void Parser::exceptionHandler(std::exception const &exc) { std::cout << d_scanner.lineNr() << " " << d_scanner.getPos() << std::endl; throw; }

#endif
