// Generated by Bisonc++ V6.03.00 on Mon, 04 Aug 2025 05:29:02 +0000

// base/comment

// $insert class.ih
#include "myparser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved_::UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN_ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok_
// which is applied. In this errTok_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved_
    {
        UNDETERMINED_   = -2,
        EOF_            = -1,
        errTok_         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    inline bool operator&(StateType lhs, StateType rhs)
    {
        return (static_cast<int>(lhs) & rhs) != 0;
    }
    enum StateTransition
    {
        ACCEPT_   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI_     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR_     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION_ = 10
    };

// Productions Info Records:
PI_ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {322, 2}, // 1: program ->  program dec_line
     {322, 1}, // 2: program ->  dec_line
     {323, 1}, // 3: btype (INT_TY) ->  INT_TY
     {323, 1}, // 4: btype (FLOAT_TY) ->  FLOAT_TY
     {323, 1}, // 5: btype (VOID_Ty) ->  VOID_Ty
     {324, 4}, // 6: dec_line (CONST) ->  CONST btype vardefs SEMICOLON
     {324, 3}, // 7: dec_line (SEMICOLON) ->  btype vardefs SEMICOLON
     {324, 1}, // 8: dec_line ->  funcdecl
     {325, 3}, // 9: vardefs (COMMA) ->  vardefs COMMA vardef
     {325, 1}, // 10: vardefs ->  vardef
     {326, 3}, // 11: vardef (IDENT) ->  IDENT ASSIGN init
     {326, 1}, // 12: vardef (IDENT) ->  IDENT
     {326, 4}, // 13: vardef (IDENT) ->  IDENT def_subs ASSIGN init
     {326, 2}, // 14: vardef (IDENT) ->  IDENT def_subs
     {327, 4}, // 15: def_subs (LBRACK) ->  def_subs LBRACK exp RBRACK
     {327, 3}, // 16: def_subs (LBRACK) ->  LBRACK exp RBRACK
     {328, 1}, // 17: init ->  exp
     {328, 3}, // 18: init (LBRACE) ->  LBRACE init_list RBRACE
     {328, 2}, // 19: init (LBRACE) ->  LBRACE RBRACE
     {329, 3}, // 20: init_list (COMMA) ->  init_list COMMA init
     {329, 1}, // 21: init_list ->  init
     {330, 6}, // 22: funcdecl (IDENT) ->  btype IDENT LPAREN fparms RPAREN block
     {330, 5}, // 23: funcdecl (IDENT) ->  btype IDENT LPAREN RPAREN block
     {331, 3}, // 24: fparms (COMMA) ->  fparms COMMA fparm
     {331, 1}, // 25: fparms ->  fparm
     {332, 2}, // 26: fparm (IDENT) ->  btype IDENT
     {332, 5}, // 27: fparm (IDENT) ->  btype IDENT LBRACK RBRACK fparm_subs
     {332, 4}, // 28: fparm (IDENT) ->  btype IDENT LBRACK RBRACK
     {333, 4}, // 29: fparm_subs (LBRACK) ->  fparm_subs LBRACK exp RBRACK
     {333, 3}, // 30: fparm_subs (LBRACK) ->  LBRACK exp RBRACK
     {334, 2}, // 31: block (LBRACE) ->  LBRACE RBRACE
     {334, 3}, // 32: block (LBRACE) ->  LBRACE items RBRACE
     {335, 2}, // 33: items ->  items stmt
     {335, 2}, // 34: items ->  items dec_line
     {335, 1}, // 35: items ->  stmt
     {335, 1}, // 36: items ->  dec_line
     {336, 4}, // 37: stmt (ASSIGN) ->  lvalue ASSIGN exp SEMICOLON
     {336, 2}, // 38: stmt (SEMICOLON) ->  exp SEMICOLON
     {336, 1}, // 39: stmt ->  block
     {336, 5}, // 40: stmt (IF) ->  IF LPAREN cond RPAREN stmt
     {336, 7}, // 41: stmt (IF) ->  IF LPAREN cond RPAREN stmt ELSE stmt
     {336, 5}, // 42: stmt (WHILE) ->  WHILE LPAREN cond RPAREN stmt
     {336, 2}, // 43: stmt (BREAK) ->  BREAK SEMICOLON
     {336, 2}, // 44: stmt (CONTINUE) ->  CONTINUE SEMICOLON
     {336, 2}, // 45: stmt (RETURN) ->  RETURN SEMICOLON
     {336, 3}, // 46: stmt (RETURN) ->  RETURN exp SEMICOLON
     {336, 1}, // 47: stmt (SEMICOLON) ->  SEMICOLON
     {337, 1}, // 48: cond ->  lorexp
     {338, 1}, // 49: lorexp ->  landexp
     {338, 3}, // 50: lorexp (OR) ->  lorexp OR landexp
     {339, 1}, // 51: landexp ->  eqexp
     {339, 3}, // 52: landexp (AND) ->  landexp AND eqexp
     {340, 1}, // 53: eqexp ->  relexp
     {340, 3}, // 54: eqexp (EQ) ->  eqexp EQ relexp
     {340, 3}, // 55: eqexp (NEQ) ->  eqexp NEQ relexp
     {341, 1}, // 56: relexp ->  addexp
     {341, 3}, // 57: relexp (LT) ->  relexp LT addexp
     {341, 3}, // 58: relexp (LE) ->  relexp LE addexp
     {341, 3}, // 59: relexp (GT) ->  relexp GT addexp
     {341, 3}, // 60: relexp (GE) ->  relexp GE addexp
     {342, 1}, // 61: exp ->  addexp
     {343, 1}, // 62: addexp ->  mulexp
     {343, 3}, // 63: addexp (PLUS) ->  addexp PLUS mulexp
     {343, 3}, // 64: addexp (MINUS) ->  addexp MINUS mulexp
     {344, 1}, // 65: mulexp ->  unaryexp
     {344, 3}, // 66: mulexp (TIMES) ->  mulexp TIMES unaryexp
     {344, 3}, // 67: mulexp (DIVIDE) ->  mulexp DIVIDE unaryexp
     {344, 3}, // 68: mulexp (MODULE) ->  mulexp MODULE unaryexp
     {345, 1}, // 69: unaryexp ->  primaryexp
     {345, 4}, // 70: unaryexp (IDENT) ->  IDENT LPAREN rparms RPAREN
     {345, 3}, // 71: unaryexp (IDENT) ->  IDENT LPAREN RPAREN
     {345, 2}, // 72: unaryexp (PLUS) ->  PLUS unaryexp
     {345, 2}, // 73: unaryexp (MINUS) ->  MINUS unaryexp
     {345, 2}, // 74: unaryexp (NEG) ->  NEG unaryexp
     {346, 3}, // 75: rparms (COMMA) ->  rparms COMMA rparm
     {346, 1}, // 76: rparms ->  rparm
     {347, 1}, // 77: rparm ->  exp
     {348, 3}, // 78: primaryexp (LPAREN) ->  LPAREN exp RPAREN
     {348, 1}, // 79: primaryexp ->  lvalue
     {348, 1}, // 80: primaryexp (INT) ->  INT
     {348, 1}, // 81: primaryexp (FLOAT) ->  FLOAT
     {349, 1}, // 82: lvalue (IDENT) ->  IDENT
     {349, 4}, // 83: lvalue (LBRACK) ->  lvalue LBRACK exp RBRACK
     {350, 1}, // 84: program_$ ->  program
};

// State info and SR_ transitions for each state.


SR_ s_0[] =
{
    { { REQ_TOKEN}, { 9} },            
    { {       322}, { 1} }, // program 
    { {       324}, { 2} }, // dec_line
    { {       274}, { 3} }, // CONST   
    { {       323}, { 4} }, // btype   
    { {       330}, { 5} }, // funcdecl
    { {       275}, { 6} }, // INT_TY  
    { {       276}, { 7} }, // FLOAT_TY
    { {       277}, { 8} }, // VOID_Ty 
    { {         0}, { 0} },            
};

SR_ s_1[] =
{
    { { REQ_TOKEN}, {       9} },            
    { {       324}, {       9} }, // dec_line
    { {       274}, {       3} }, // CONST   
    { {       323}, {       4} }, // btype   
    { {       330}, {       5} }, // funcdecl
    { {       275}, {       6} }, // INT_TY  
    { {       276}, {       7} }, // FLOAT_TY
    { {       277}, {       8} }, // VOID_Ty 
    { {      EOF_}, { ACCEPT_} },            
    { {         0}, {       0} },            
};

SR_ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR_ s_3[] =
{
    { { REQ_TOKEN}, {  5} },            
    { {       323}, { 10} }, // btype   
    { {       275}, {  6} }, // INT_TY  
    { {       276}, {  7} }, // FLOAT_TY
    { {       277}, {  8} }, // VOID_Ty 
    { {         0}, {  0} },            
};

SR_ s_4[] =
{
    { { REQ_TOKEN}, {  4} },           
    { {       325}, { 11} }, // vardefs
    { {       257}, { 12} }, // IDENT  
    { {       326}, { 13} }, // vardef 
    { {         0}, {  0} },           
};

SR_ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR_ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR_ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR_ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR_ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR_ s_10[] =
{
    { { REQ_TOKEN}, {  4} },           
    { {       325}, { 14} }, // vardefs
    { {       326}, { 13} }, // vardef 
    { {       257}, { 15} }, // IDENT  
    { {         0}, {  0} },           
};

SR_ s_11[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       261}, { 16} }, // SEMICOLON
    { {       260}, { 17} }, // COMMA    
    { {         0}, {  0} },             
};

SR_ s_12[] =
{
    { { REQ_DEF}, {   5} },            
    { {     262}, {  18} }, // LPAREN  
    { {     278}, {  19} }, // ASSIGN  
    { {     327}, {  20} }, // def_subs
    { {     264}, {  21} }, // LBRACK  
    { {       0}, { -12} },            
};

SR_ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR_ s_14[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       261}, { 22} }, // SEMICOLON
    { {       260}, { 17} }, // COMMA    
    { {         0}, {  0} },             
};

SR_ s_15[] =
{
    { { REQ_DEF}, {   4} },            
    { {     278}, {  19} }, // ASSIGN  
    { {     327}, {  20} }, // def_subs
    { {     264}, {  21} }, // LBRACK  
    { {       0}, { -12} },            
};

SR_ s_16[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR_ s_17[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       326}, { 23} }, // vardef
    { {       257}, { 15} }, // IDENT 
    { {         0}, {  0} },          
};

SR_ s_18[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       331}, { 24} }, // fparms  
    { {       263}, { 25} }, // RPAREN  
    { {       332}, { 26} }, // fparm   
    { {       323}, { 27} }, // btype   
    { {       275}, {  6} }, // INT_TY  
    { {       276}, {  7} }, // FLOAT_TY
    { {       277}, {  8} }, // VOID_Ty 
    { {         0}, {  0} },            
};

SR_ s_19[] =
{
    { { REQ_TOKEN}, { 16} },              
    { {       328}, { 28} }, // init      
    { {       342}, { 29} }, // exp       
    { {       266}, { 30} }, // LBRACE    
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_20[] =
{
    { { REQ_DEF}, {   3} },          
    { {     278}, {  43} }, // ASSIGN
    { {     264}, {  44} }, // LBRACK
    { {       0}, { -14} },          
};

SR_ s_21[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       342}, { 45} }, // exp       
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_22[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR_ s_23[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR_ s_24[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       263}, { 46} }, // RPAREN
    { {       260}, { 47} }, // COMMA 
    { {         0}, {  0} },          
};

SR_ s_25[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       334}, { 48} }, // block 
    { {       266}, { 49} }, // LBRACE
    { {         0}, {  0} },          
};

SR_ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR_ s_27[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       257}, { 50} }, // IDENT
    { {         0}, {  0} },         
};

SR_ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR_ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR_ s_30[] =
{
    { { REQ_TOKEN}, { 18} },              
    { {       329}, { 51} }, // init_list 
    { {       267}, { 52} }, // RBRACE    
    { {       328}, { 53} }, // init      
    { {       342}, { 29} }, // exp       
    { {       266}, { 30} }, // LBRACE    
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_31[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  54} }, // PLUS 
    { {     289}, {  55} }, // MINUS
    { {       0}, { -61} },         
};

SR_ s_32[] =
{
    { { REQ_DEF}, {   4} },          
    { {     290}, {  56} }, // TIMES 
    { {     291}, {  57} }, // DIVIDE
    { {     292}, {  58} }, // MODULE
    { {       0}, { -62} },          
};

SR_ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR_ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR_ s_35[] =
{
    { { REQ_DEF}, {   2} },          
    { {     262}, {  59} }, // LPAREN
    { {       0}, { -82} },          
};

SR_ s_36[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       345}, { 60} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_37[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       345}, { 61} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_38[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       345}, { 62} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_39[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       342}, { 63} }, // exp       
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_40[] =
{
    { { REQ_DEF}, {   2} },          
    { {     264}, {  64} }, // LBRACK
    { {       0}, { -79} },          
};

SR_ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR_ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR_ s_43[] =
{
    { { REQ_TOKEN}, { 16} },              
    { {       328}, { 65} }, // init      
    { {       342}, { 29} }, // exp       
    { {       266}, { 30} }, // LBRACE    
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_44[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       342}, { 66} }, // exp       
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_45[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       265}, { 67} }, // RBRACK
    { {         0}, {  0} },          
};

SR_ s_46[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       334}, { 68} }, // block 
    { {       266}, { 49} }, // LBRACE
    { {         0}, {  0} },          
};

SR_ s_47[] =
{
    { { REQ_TOKEN}, {  6} },            
    { {       332}, { 69} }, // fparm   
    { {       323}, { 27} }, // btype   
    { {       275}, {  6} }, // INT_TY  
    { {       276}, {  7} }, // FLOAT_TY
    { {       277}, {  8} }, // VOID_Ty 
    { {         0}, {  0} },            
};

SR_ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR_ s_49[] =
{
    { { REQ_TOKEN}, { 32} },              
    { {       267}, { 70} }, // RBRACE    
    { {       335}, { 71} }, // items     
    { {       336}, { 72} }, // stmt      
    { {       324}, { 73} }, // dec_line  
    { {       349}, { 74} }, // lvalue    
    { {       342}, { 75} }, // exp       
    { {       334}, { 76} }, // block     
    { {       268}, { 77} }, // IF        
    { {       270}, { 78} }, // WHILE     
    { {       271}, { 79} }, // BREAK     
    { {       272}, { 80} }, // CONTINUE  
    { {       273}, { 81} }, // RETURN    
    { {       261}, { 82} }, // SEMICOLON 
    { {       274}, {  3} }, // CONST     
    { {       323}, {  4} }, // btype     
    { {       330}, {  5} }, // funcdecl  
    { {       257}, { 35} }, // IDENT     
    { {       343}, { 31} }, // addexp    
    { {       266}, { 49} }, // LBRACE    
    { {       275}, {  6} }, // INT_TY    
    { {       276}, {  7} }, // FLOAT_TY  
    { {       277}, {  8} }, // VOID_Ty   
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_50[] =
{
    { { REQ_DEF}, {   2} },          
    { {     264}, {  83} }, // LBRACK
    { {       0}, { -26} },          
};

SR_ s_51[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       267}, { 84} }, // RBRACE
    { {       260}, { 85} }, // COMMA 
    { {         0}, {  0} },          
};

SR_ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR_ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR_ s_54[] =
{
    { { REQ_TOKEN}, { 12} },              
    { {       344}, { 86} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_55[] =
{
    { { REQ_TOKEN}, { 12} },              
    { {       344}, { 87} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_56[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       345}, { 88} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_57[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       345}, { 89} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_58[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       345}, { 90} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_59[] =
{
    { { REQ_TOKEN}, { 17} },              
    { {       346}, { 91} }, // rparms    
    { {       263}, { 92} }, // RPAREN    
    { {       347}, { 93} }, // rparm     
    { {       342}, { 94} }, // exp       
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR_ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR_ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR_ s_63[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 95} }, // RPAREN
    { {         0}, {  0} },          
};

SR_ s_64[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       342}, { 96} }, // exp       
    { {       343}, { 31} }, // addexp    
    { {       344}, { 32} }, // mulexp    
    { {       345}, { 33} }, // unaryexp  
    { {       348}, { 34} }, // primaryexp
    { {       257}, { 35} }, // IDENT     
    { {       288}, { 36} }, // PLUS      
    { {       289}, { 37} }, // MINUS     
    { {       281}, { 38} }, // NEG       
    { {       262}, { 39} }, // LPAREN    
    { {       349}, { 40} }, // lvalue    
    { {       258}, { 41} }, // INT       
    { {       259}, { 42} }, // FLOAT     
    { {         0}, {  0} },              
};

SR_ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR_ s_66[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       265}, { 97} }, // RBRACK
    { {         0}, {  0} },          
};

SR_ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR_ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR_ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR_ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR_ s_71[] =
{
    { { REQ_TOKEN}, {  31} },              
    { {       267}, {  98} }, // RBRACE    
    { {       336}, {  99} }, // stmt      
    { {       324}, { 100} }, // dec_line  
    { {       349}, {  74} }, // lvalue    
    { {       342}, {  75} }, // exp       
    { {       334}, {  76} }, // block     
    { {       268}, {  77} }, // IF        
    { {       270}, {  78} }, // WHILE     
    { {       271}, {  79} }, // BREAK     
    { {       272}, {  80} }, // CONTINUE  
    { {       273}, {  81} }, // RETURN    
    { {       261}, {  82} }, // SEMICOLON 
    { {       274}, {   3} }, // CONST     
    { {       323}, {   4} }, // btype     
    { {       330}, {   5} }, // funcdecl  
    { {       257}, {  35} }, // IDENT     
    { {       343}, {  31} }, // addexp    
    { {       266}, {  49} }, // LBRACE    
    { {       275}, {   6} }, // INT_TY    
    { {       276}, {   7} }, // FLOAT_TY  
    { {       277}, {   8} }, // VOID_Ty   
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR_ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR_ s_74[] =
{
    { { REQ_DEF}, {   3} },          
    { {     278}, { 101} }, // ASSIGN
    { {     264}, {  64} }, // LBRACK
    { {       0}, { -79} },          
};

SR_ s_75[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       261}, { 102} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR_ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR_ s_77[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       262}, { 103} }, // LPAREN
    { {         0}, {   0} },          
};

SR_ s_78[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       262}, { 104} }, // LPAREN
    { {         0}, {   0} },          
};

SR_ s_79[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       261}, { 105} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR_ s_80[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       261}, { 106} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR_ s_81[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       261}, { 107} }, // SEMICOLON 
    { {       342}, { 108} }, // exp       
    { {       343}, {  31} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR_ s_83[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       265}, { 109} }, // RBRACK
    { {         0}, {   0} },          
};

SR_ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR_ s_85[] =
{
    { { REQ_TOKEN}, {  16} },              
    { {       328}, { 110} }, // init      
    { {       342}, {  29} }, // exp       
    { {       266}, {  30} }, // LBRACE    
    { {       343}, {  31} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_86[] =
{
    { { REQ_DEF}, {   4} },          
    { {     290}, {  56} }, // TIMES 
    { {     291}, {  57} }, // DIVIDE
    { {     292}, {  58} }, // MODULE
    { {       0}, { -63} },          
};

SR_ s_87[] =
{
    { { REQ_DEF}, {   4} },          
    { {     290}, {  56} }, // TIMES 
    { {     291}, {  57} }, // DIVIDE
    { {     292}, {  58} }, // MODULE
    { {       0}, { -64} },          
};

SR_ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR_ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR_ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR_ s_91[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       263}, { 111} }, // RPAREN
    { {       260}, { 112} }, // COMMA 
    { {         0}, {   0} },          
};

SR_ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR_ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR_ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR_ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR_ s_96[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       265}, { 113} }, // RBRACK
    { {         0}, {   0} },          
};

SR_ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR_ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR_ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR_ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR_ s_101[] =
{
    { { REQ_TOKEN}, {  14} },              
    { {       342}, { 114} }, // exp       
    { {       343}, {  31} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR_ s_103[] =
{
    { { REQ_TOKEN}, {  18} },              
    { {       337}, { 115} }, // cond      
    { {       338}, { 116} }, // lorexp    
    { {       339}, { 117} }, // landexp   
    { {       340}, { 118} }, // eqexp     
    { {       341}, { 119} }, // relexp    
    { {       343}, { 120} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_104[] =
{
    { { REQ_TOKEN}, {  18} },              
    { {       337}, { 121} }, // cond      
    { {       338}, { 116} }, // lorexp    
    { {       339}, { 117} }, // landexp   
    { {       340}, { 118} }, // eqexp     
    { {       341}, { 119} }, // relexp    
    { {       343}, { 120} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR_ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR_ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR_ s_108[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       261}, { 122} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR_ s_109[] =
{
    { { REQ_DEF}, {   3} },              
    { {     333}, { 123} }, // fparm_subs
    { {     264}, { 124} }, // LBRACK    
    { {       0}, { -28} },              
};

SR_ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR_ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR_ s_112[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       347}, { 125} }, // rparm     
    { {       342}, {  94} }, // exp       
    { {       343}, {  31} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR_ s_114[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       261}, { 126} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR_ s_115[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       263}, { 127} }, // RPAREN
    { {         0}, {   0} },          
};

SR_ s_116[] =
{
    { { REQ_DEF}, {   2} },      
    { {     279}, { 128} }, // OR
    { {       0}, { -48} },      
};

SR_ s_117[] =
{
    { { REQ_DEF}, {   2} },       
    { {     280}, { 129} }, // AND
    { {       0}, { -49} },       
};

SR_ s_118[] =
{
    { { REQ_DEF}, {   3} },       
    { {     282}, { 130} }, // EQ 
    { {     283}, { 131} }, // NEQ
    { {       0}, { -51} },       
};

SR_ s_119[] =
{
    { { REQ_DEF}, {   5} },      
    { {     284}, { 132} }, // LT
    { {     285}, { 133} }, // LE
    { {     286}, { 134} }, // GT
    { {     287}, { 135} }, // GE
    { {       0}, { -53} },      
};

SR_ s_120[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  54} }, // PLUS 
    { {     289}, {  55} }, // MINUS
    { {       0}, { -56} },         
};

SR_ s_121[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       263}, { 136} }, // RPAREN
    { {         0}, {   0} },          
};

SR_ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR_ s_123[] =
{
    { { REQ_DEF}, {   2} },          
    { {     264}, { 137} }, // LBRACK
    { {       0}, { -27} },          
};

SR_ s_124[] =
{
    { { REQ_TOKEN}, {  14} },              
    { {       342}, { 138} }, // exp       
    { {       343}, {  31} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR_ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR_ s_127[] =
{
    { { REQ_TOKEN}, {  23} },              
    { {       336}, { 139} }, // stmt      
    { {       349}, {  74} }, // lvalue    
    { {       342}, {  75} }, // exp       
    { {       334}, {  76} }, // block     
    { {       268}, {  77} }, // IF        
    { {       270}, {  78} }, // WHILE     
    { {       271}, {  79} }, // BREAK     
    { {       272}, {  80} }, // CONTINUE  
    { {       273}, {  81} }, // RETURN    
    { {       261}, {  82} }, // SEMICOLON 
    { {       257}, {  35} }, // IDENT     
    { {       343}, {  31} }, // addexp    
    { {       266}, {  49} }, // LBRACE    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_128[] =
{
    { { REQ_TOKEN}, {  16} },              
    { {       339}, { 140} }, // landexp   
    { {       340}, { 118} }, // eqexp     
    { {       341}, { 119} }, // relexp    
    { {       343}, { 120} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_129[] =
{
    { { REQ_TOKEN}, {  15} },              
    { {       340}, { 141} }, // eqexp     
    { {       341}, { 119} }, // relexp    
    { {       343}, { 120} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_130[] =
{
    { { REQ_TOKEN}, {  14} },              
    { {       341}, { 142} }, // relexp    
    { {       343}, { 120} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_131[] =
{
    { { REQ_TOKEN}, {  14} },              
    { {       341}, { 143} }, // relexp    
    { {       343}, { 120} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_132[] =
{
    { { REQ_TOKEN}, {  13} },              
    { {       343}, { 144} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_133[] =
{
    { { REQ_TOKEN}, {  13} },              
    { {       343}, { 145} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_134[] =
{
    { { REQ_TOKEN}, {  13} },              
    { {       343}, { 146} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_135[] =
{
    { { REQ_TOKEN}, {  13} },              
    { {       343}, { 147} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_136[] =
{
    { { REQ_TOKEN}, {  23} },              
    { {       336}, { 148} }, // stmt      
    { {       349}, {  74} }, // lvalue    
    { {       342}, {  75} }, // exp       
    { {       334}, {  76} }, // block     
    { {       268}, {  77} }, // IF        
    { {       270}, {  78} }, // WHILE     
    { {       271}, {  79} }, // BREAK     
    { {       272}, {  80} }, // CONTINUE  
    { {       273}, {  81} }, // RETURN    
    { {       261}, {  82} }, // SEMICOLON 
    { {       257}, {  35} }, // IDENT     
    { {       343}, {  31} }, // addexp    
    { {       266}, {  49} }, // LBRACE    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_137[] =
{
    { { REQ_TOKEN}, {  14} },              
    { {       342}, { 149} }, // exp       
    { {       343}, {  31} }, // addexp    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       257}, {  35} }, // IDENT     
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       349}, {  40} }, // lvalue    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_138[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       265}, { 150} }, // RBRACK
    { {         0}, {   0} },          
};

SR_ s_139[] =
{
    { { REQ_DEF}, {   2} },        
    { {     269}, { 151} }, // ELSE
    { {       0}, { -40} },        
};

SR_ s_140[] =
{
    { { REQ_DEF}, {   2} },       
    { {     280}, { 129} }, // AND
    { {       0}, { -50} },       
};

SR_ s_141[] =
{
    { { REQ_DEF}, {   3} },       
    { {     282}, { 130} }, // EQ 
    { {     283}, { 131} }, // NEQ
    { {       0}, { -52} },       
};

SR_ s_142[] =
{
    { { REQ_DEF}, {   5} },      
    { {     284}, { 132} }, // LT
    { {     285}, { 133} }, // LE
    { {     286}, { 134} }, // GT
    { {     287}, { 135} }, // GE
    { {       0}, { -54} },      
};

SR_ s_143[] =
{
    { { REQ_DEF}, {   5} },      
    { {     284}, { 132} }, // LT
    { {     285}, { 133} }, // LE
    { {     286}, { 134} }, // GT
    { {     287}, { 135} }, // GE
    { {       0}, { -55} },      
};

SR_ s_144[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  54} }, // PLUS 
    { {     289}, {  55} }, // MINUS
    { {       0}, { -57} },         
};

SR_ s_145[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  54} }, // PLUS 
    { {     289}, {  55} }, // MINUS
    { {       0}, { -58} },         
};

SR_ s_146[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  54} }, // PLUS 
    { {     289}, {  55} }, // MINUS
    { {       0}, { -59} },         
};

SR_ s_147[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  54} }, // PLUS 
    { {     289}, {  55} }, // MINUS
    { {       0}, { -60} },         
};

SR_ s_148[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR_ s_149[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       265}, { 152} }, // RBRACK
    { {         0}, {   0} },          
};

SR_ s_150[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR_ s_151[] =
{
    { { REQ_TOKEN}, {  23} },              
    { {       336}, { 153} }, // stmt      
    { {       349}, {  74} }, // lvalue    
    { {       342}, {  75} }, // exp       
    { {       334}, {  76} }, // block     
    { {       268}, {  77} }, // IF        
    { {       270}, {  78} }, // WHILE     
    { {       271}, {  79} }, // BREAK     
    { {       272}, {  80} }, // CONTINUE  
    { {       273}, {  81} }, // RETURN    
    { {       261}, {  82} }, // SEMICOLON 
    { {       257}, {  35} }, // IDENT     
    { {       343}, {  31} }, // addexp    
    { {       266}, {  49} }, // LBRACE    
    { {       344}, {  32} }, // mulexp    
    { {       345}, {  33} }, // unaryexp  
    { {       348}, {  34} }, // primaryexp
    { {       288}, {  36} }, // PLUS      
    { {       289}, {  37} }, // MINUS     
    { {       281}, {  38} }, // NEG       
    { {       262}, {  39} }, // LPAREN    
    { {       258}, {  41} }, // INT       
    { {       259}, {  42} }, // FLOAT     
    { {         0}, {   0} },              
};

SR_ s_152[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR_ s_153[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};


// State array:
SR_ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved_::UNDETERMINED_),
    // $insert baseclasscode
    d_requiredTokens_(0)
{
}

// base/clearin
void ParserBase::clearin_()
{
    d_nErrors_ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved_::UNDETERMINED_;
    d_next = TokenPair{ Reserved_::UNDETERMINED_, STYPE_{} };
    d_recovery = false;
    d_acceptedTokens_ = d_requiredTokens_;
    d_val_ = STYPE_{};

    push_(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases_ = false;
    d_debug_ = mode;
}

void ParserBase::setDebug(DebugMode_ mode)
{
    d_actionCases_ = mode & ACTIONCASES;
    d_debug_ =       mode & ON;
}

// base/lex
void ParserBase::lex_(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved_::EOF_;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup_() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR_ const *sr = s_state[d_state];
    SR_ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN_;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop_(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken_()
{
    d_token = d_next.first;
    d_val_ = std::move(d_next.second);

    d_next.first = Reserved_::UNDETERMINED_;
}

// base/push
void ParserBase::push_(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize_() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION_;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val_) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken_(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val_) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken_()
{
    if (d_token != Reserved_::UNDETERMINED_)
        pushToken_(d_token);
}

// base/reduce
void ParserBase::reduce_(int rule)
{
    PI_ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop_(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift_(int action)
{
    push_(action);
    popToken_();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens_ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery_()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken_(Reserved_::errTok_);      // specify errTok_ as next token
    push_(lookup_());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top_() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery_()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens_ >= d_requiredTokens_)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors_;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top_()][0].d_type & ERR_ITEM))
    {
        pop_();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle_ for details.

    startRecovery_();
}

// derived/executeaction
void Parser::executeAction_(int production)
try
{
    if (token_() != Reserved_::UNDETERMINED_)
        pushToken_(token_());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 64 "aaac.y"
        {
         vs_(0).dlist->patchTo(vs_(-1).TU);
         d_val_.TU = vs_(-1).TU;
        }
        break;

        case 2:
#line 68 "aaac.y"
        {
         d_val_.TU = TU = new TUDecl(d_scanner.getPos());
         vs_(0).dlist->patchTo(d_val_.TU);
        }
        break;

        case 3:
#line 75 "aaac.y"
        { d_val_.sval = new std::string("int"); }
        break;

        case 4:
#line 76 "aaac.y"
        { d_val_.sval = new std::string("float"); }
        break;

        case 5:
#line 77 "aaac.y"
        { d_val_.sval = new std::string("void"); }
        break;

        case 6:
#line 81 "aaac.y"
        {
         
         vs_(-1).dlist->patch(*vs_(-2).sval,true);
         delete vs_(-2).sval;
         d_val_.dlist = vs_(-1).dlist;
        }
        break;

        case 7:
#line 87 "aaac.y"
        {
         vs_(-1).dlist->patch(*vs_(-2).sval);
         d_val_.dlist = vs_(-1).dlist;
        }
        break;

        case 8:
#line 91 "aaac.y"
        {
         auto ptr = new DeclList();
         ptr->append(vs_(0).fdecl);
         d_val_.dlist = ptr;
        }
        break;

        case 9:
#line 99 "aaac.y"
        {
         
         d_val_.dlist = vs_(-2).dlist->append(vs_(0).vdecl);
        }
        break;

        case 10:
#line 103 "aaac.y"
        {
         
         d_val_.dlist = new DeclList();
         d_val_.dlist->append(vs_(0).vdecl);
        }
        break;

        case 11:
#line 111 "aaac.y"
        {
         
         d_val_.vdecl = new VarDecl(d_scanner.getPos(),"",*vs_(-2).sval,vs_(0).expr);
        }
        break;

        case 12:
#line 115 "aaac.y"
        {
         d_val_.vdecl = new VarDecl(d_scanner.getPos(),"",*vs_(0).sval,nullptr);
        }
        break;

        case 13:
#line 118 "aaac.y"
        {
         auto ptr = new ArrayDecl(d_scanner.getPos(),"",*vs_(-3).sval,vs_(0).expr);
         vs_(-2).sub_list->patchTo(ptr);
         delete vs_(-2).sub_list;
         d_val_.vdecl = ptr;
        }
        break;

        case 14:
#line 124 "aaac.y"
        {
         
         auto ptr = new ArrayDecl(d_scanner.getPos(),"",*vs_(-1).sval,nullptr);
         
         vs_(0).sub_list->patchTo(ptr);
         
         delete vs_(0).sub_list;
         d_val_.vdecl = ptr;
        }
        break;

        case 15:
#line 136 "aaac.y"
        {
         
         d_val_.sub_list = vs_(-3).sub_list->append(vs_(-1).expr);
        }
        break;

        case 16:
#line 140 "aaac.y"
        {
         d_val_.sub_list = new SubList();
         d_val_.sub_list->append(vs_(-1).expr);
        }
        break;

        case 17:
#line 147 "aaac.y"
        { 
         d_val_.expr = vs_(0).expr; 
         
        }
        break;

        case 18:
#line 151 "aaac.y"
        {
         d_val_.expr = vs_(-1).init_list; 
         
        }
        break;

        case 19:
#line 155 "aaac.y"
        {
         d_val_.expr = new InitList(d_scanner.getPos());
        }
        break;

        case 20:
#line 161 "aaac.y"
        {
         d_val_.init_list = vs_(-2).init_list->append(vs_(0).expr);
        }
        break;

        case 21:
#line 164 "aaac.y"
        {
         
         d_val_.init_list = new InitList(d_scanner.getPos());
         d_val_.init_list->append(vs_(0).expr);
        }
        break;

        case 22:
#line 172 "aaac.y"
        {
         d_val_.fdecl = new FuncDecl(d_scanner.getPos(), *vs_(-5).sval, *vs_(-4).sval, vs_(-2).fparm_list, vs_(0).compond_stmt);
        }
        break;

        case 23:
#line 175 "aaac.y"
        {
         d_val_.fdecl = new FuncDecl(d_scanner.getPos(), *vs_(-4).sval, *vs_(-3).sval, new FParmList(), vs_(0).compond_stmt);
        }
        break;

        case 24:
#line 181 "aaac.y"
        {
         vs_(-2).fparm_list->push_back(vs_(0).vdecl);
         d_val_.fparm_list = vs_(-2).fparm_list;
        }
        break;

        case 25:
#line 185 "aaac.y"
        {
         d_val_.fparm_list = new FParmList();
         d_val_.fparm_list->push_back(vs_(0).vdecl);
        }
        break;

        case 26:
#line 192 "aaac.y"
        {
         d_val_.vdecl = new VarDecl(d_scanner.getPos(),*vs_(-1).sval, *vs_(0).sval, nullptr);
         delete vs_(-1).sval;
        }
        break;

        case 27:
#line 196 "aaac.y"
        {
         vs_(0).sub_list->prepend(new EmptyExpr(d_scanner.getPos()));
         auto ptr = new ArrayDecl(d_scanner.getPos(),*vs_(-4).sval, *vs_(-3).sval, nullptr);
         vs_(0).sub_list->patchTo(ptr);
         d_val_.vdecl = ptr;
         delete vs_(-4).sval;
        }
        break;

        case 28:
#line 203 "aaac.y"
        {
         auto ptr = new ArrayDecl(d_scanner.getPos(), *vs_(-3).sval, *vs_(-2).sval, nullptr);
         ptr->appendSubscript(new EmptyExpr(d_scanner.getPos()));
         d_val_.vdecl = ptr;
         delete vs_(-3).sval;
        }
        break;

        case 29:
#line 212 "aaac.y"
        {
         d_val_.sub_list = vs_(-3).sub_list->append(vs_(-1).expr);
        }
        break;

        case 30:
#line 215 "aaac.y"
        {
         d_val_.sub_list = new SubList();
         d_val_.sub_list->append(vs_(-1).expr);
        }
        break;

        case 31:
#line 222 "aaac.y"
        {
         d_val_.compond_stmt = new CompondStmt(d_scanner.getPos());
        }
        break;

        case 32:
#line 225 "aaac.y"
        {
         d_val_.compond_stmt = vs_(-1).compond_stmt;
        }
        break;

        case 33:
#line 231 "aaac.y"
        {
         vs_(-1).compond_stmt->appendStmt(vs_(0).stmt);
         d_val_.compond_stmt = vs_(-1).compond_stmt;
        }
        break;

        case 34:
#line 235 "aaac.y"
        {
         vs_(0).dlist->patchTo(vs_(-1).compond_stmt);
         d_val_.compond_stmt = vs_(-1).compond_stmt;
        }
        break;

        case 35:
#line 239 "aaac.y"
        {
         d_val_.compond_stmt = new CompondStmt(d_scanner.getPos());
         d_val_.compond_stmt->appendStmt(vs_(0).stmt);
        }
        break;

        case 36:
#line 243 "aaac.y"
        {
         d_val_.compond_stmt = new CompondStmt(d_scanner.getPos());
         vs_(0).dlist->patchTo(d_val_.compond_stmt);
        }
        break;

        case 37:
#line 250 "aaac.y"
        {
         d_val_.stmt = new AssignStmt(d_scanner.getPos(), vs_(-3).var, vs_(-1).expr);
        }
        break;

        case 38:
#line 253 "aaac.y"
        {
         d_val_.stmt = vs_(-1).expr;
        }
        break;

        case 39:
#line 256 "aaac.y"
        {
         d_val_.stmt = vs_(0).compond_stmt;
        }
        break;

        case 40:
#line 259 "aaac.y"
        {
         d_val_.stmt = new IfStmt(d_scanner.getPos(),vs_(-2).expr,vs_(0).stmt,nullptr);
        }
        break;

        case 41:
#line 262 "aaac.y"
        {
         d_val_.stmt = new IfStmt(d_scanner.getPos(),vs_(-4).expr,vs_(-2).stmt,vs_(0).stmt);
        }
        break;

        case 42:
#line 265 "aaac.y"
        {
         d_val_.stmt = new WhileStmt(d_scanner.getPos(),vs_(-2).expr,vs_(0).stmt);
        }
        break;

        case 43:
#line 268 "aaac.y"
        {
         d_val_.stmt = new BreakStmt(d_scanner.getPos());
        }
        break;

        case 44:
#line 271 "aaac.y"
        {
         d_val_.stmt = new ContinueStmt(d_scanner.getPos());
        }
        break;

        case 45:
#line 274 "aaac.y"
        {
         d_val_.stmt = new ReturnStmt(d_scanner.getPos(),nullptr);
        }
        break;

        case 46:
#line 277 "aaac.y"
        {
         d_val_.stmt = new ReturnStmt(d_scanner.getPos(),vs_(-1).expr);
        }
        break;

        case 47:
#line 280 "aaac.y"
        {
         d_val_.stmt = new EmptyStmt(d_scanner.getPos());
        }
        break;

        case 48:
#line 286 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 49:
#line 292 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 50:
#line 295 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), OR_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 51:
#line 301 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 52:
#line 304 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), AND_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 53:
#line 310 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 54:
#line 313 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), EQ_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 55:
#line 317 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), NEQ_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 56:
#line 323 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 57:
#line 326 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), LT_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 58:
#line 329 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), LE_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 59:
#line 332 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), GT_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 60:
#line 335 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), GE_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 61:
#line 341 "aaac.y"
        { 
         d_val_.expr = vs_(0).expr; 
         
        }
        break;

        case 62:
#line 348 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 63:
#line 351 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), BinaryOp::PLUS_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 64:
#line 354 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), BinaryOp::MINUS_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 65:
#line 360 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 66:
#line 363 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), BinaryOp::TIMES_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 67:
#line 366 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), BinaryOp::DIVIDE_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 68:
#line 369 "aaac.y"
        {
         d_val_.expr = new BinaryOperator(d_scanner.getPos(), BinaryOp::MODULE_OP, vs_(-2).expr, vs_(0).expr);
        }
        break;

        case 69:
#line 375 "aaac.y"
        {
         d_val_.expr = vs_(0).expr;
        }
        break;

        case 70:
#line 378 "aaac.y"
        {
        
         d_val_.expr = new CallExpr(d_scanner.getPos(), *vs_(-3).sval, vs_(-1).rparm_list);
        }
        break;

        case 71:
#line 382 "aaac.y"
        {
         d_val_.expr = new CallExpr(d_scanner.getPos(), *vs_(-2).sval, new RparmList());
        }
        break;

        case 72:
#line 385 "aaac.y"
        {
         d_val_.expr = new UnaryOperator(d_scanner.getPos(), UnaryOp::Positive, vs_(0).expr);
        }
        break;

        case 73:
#line 388 "aaac.y"
        {
         d_val_.expr = new UnaryOperator(d_scanner.getPos(), UnaryOp::Negative, vs_(0).expr);
        }
        break;

        case 74:
#line 391 "aaac.y"
        {
         d_val_.expr = new UnaryOperator(d_scanner.getPos(), UnaryOp::Negate, vs_(0).expr);
        }
        break;

        case 75:
#line 397 "aaac.y"
        {
         vs_(-2).rparm_list->push_back(vs_(0).expr);
         d_val_.rparm_list = vs_(-2).rparm_list;
        }
        break;

        case 76:
#line 401 "aaac.y"
        {
         d_val_.rparm_list = new RparmList({vs_(0).expr});
        }
        break;

        case 77:
#line 406 "aaac.y"
        { d_val_.expr = vs_(0).expr; }
        break;

        case 78:
#line 409 "aaac.y"
        {
         d_val_.expr = vs_(-1).expr;
        }
        break;

        case 79:
#line 412 "aaac.y"
        {
         d_val_.expr = vs_(0).var;
        }
        break;

        case 80:
#line 415 "aaac.y"
        {
         d_val_.expr = new IntLiteral(d_scanner.getPos(), vs_(0).ival);
        }
        break;

        case 81:
#line 418 "aaac.y"
        {
         d_val_.expr = new FloatLiteral(d_scanner.getPos(), vs_(0).dval);
        }
        break;

        case 82:
#line 424 "aaac.y"
        {
         
         d_val_.var = new Var(d_scanner.getPos(),*vs_(0).sval);
        }
        break;

        case 83:
#line 428 "aaac.y"
        {
         d_val_.var = new SubscriptVar(d_scanner.getPos(), vs_(-3).var, vs_(-1).expr);
        }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle_()
try
{
    if (s_state[state_()]->d_type & REQ_TOKEN)
        nextToken_();              // obtain next token


    int action = lookup_();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift_(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery_())
            redoToken_();
        else
            executeAction_(-action);
                                            // next token is the rule's LHS
        reduce_(-action); 
        return;
    }

    if (recovery_())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery_)
{
    if (not recovery_())
        errorRecovery_();
    else
    {
        if (token_() == Reserved_::EOF_)
            ABORT();
        popToken_();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken_()
{ 
    // If d_token is Reserved_::UNDETERMINED_ then if savedToken_() is
    // Reserved_::UNDETERMINED_ another token is obtained from lex(). Then
    // savedToken_() is assigned to d_token.

                                    // no need for a token: got one already
    if (token_() != Reserved_::UNDETERMINED_) 
    {
        return;                             
    }

    if (savedToken_() != Reserved_::UNDETERMINED_)
    {
        popToken_();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens_;       // accept another token (see
                                    // errorRecover())
        lex_(lex());
        print_();
    }
    print();
}

// derived/print
void Parser::print_()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin_.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin_();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle_();
    }
}
catch (Return_ retValue)
{
    return retValue or d_nErrors_;
}


// derived/tail


